// Designation options
export const DESIGNATION_OPTIONS = [
  { value: "CEO", label: "CEO" },
  { value: "CTO", label: "CTO" },
  { value: "CFO", label: "CFO" },
  { value: "COO", label: "COO" },
  { value: "CMO", label: "CMO" },
  { value: "VP", label: "VP" },
  { value: "Director", label: "Director" },
  { value: "Manager", label: "Manager" },
  { value: "Senior Manager", label: "Senior Manager" },
  { value: "Team Lead", label: "Team Lead" },
  { value: "Senior Developer", label: "Senior Developer" },
  { value: "Developer", label: "Developer" },
  { value: "Designer", label: "Designer" },
  { value: "Analyst", label: "Analyst" },
  { value: "Consultant", label: "Consultant" },
  { value: "Entrepreneur", label: "Entrepreneur" },
  { value: "Founder", label: "Founder" },
  { value: "Co-Founder", label: "Co-Founder" },
  { value: "Owner", label: "Owner" },
  { value: "Partner", label: "Partner" },
  { value: "Others", label: "Others" },
];

// Sector options
export const SECTOR_OPTIONS = [
  { value: "Technology", label: "Technology" },
  { value: "Healthcare", label: "Healthcare" },
  { value: "Finance", label: "Finance" },
  { value: "Education", label: "Education" },
  { value: "Manufacturing", label: "Manufacturing" },
  { value: "Retail", label: "Retail" },
  { value: "Real Estate", label: "Real Estate" },
  { value: "Energy", label: "Energy" },
  { value: "Transportation", label: "Transportation" },
  { value: "Agriculture", label: "Agriculture" },
  { value: "Food & Beverage", label: "Food & Beverage" },
  { value: "Media & Entertainment", label: "Media & Entertainment" },
  { value: "Telecommunications", label: "Telecommunications" },
  { value: "Construction", label: "Construction" },
  { value: "Hospitality", label: "Hospitality" },
  { value: "Automotive", label: "Automotive" },
  { value: "Aerospace", label: "Aerospace" },
  { value: "Pharmaceuticals", label: "Pharmaceuticals" },
  { value: "Consulting", label: "Consulting" },
  { value: "Others", label: "Others" },
];

// Sub Sector options
export const SUB_SECTOR_OPTIONS = [
  { value: "Software Development", label: "Software Development" },
  { value: "IT Services", label: "IT Services" },
  { value: "E-commerce", label: "E-commerce" },
  { value: "Fintech", label: "Fintech" },
  { value: "EdTech", label: "EdTech" },
  { value: "HealthTech", label: "HealthTech" },
  { value: "Biotechnology", label: "Biotechnology" },
  { value: "Medical Devices", label: "Medical Devices" },
  { value: "Banking", label: "Banking" },
  { value: "Insurance", label: "Insurance" },
  { value: "Investment", label: "Investment" },
  { value: "Trading", label: "Trading" },
  { value: "Online Education", label: "Online Education" },
  { value: "Training", label: "Training" },
  { value: "Electronics", label: "Electronics" },
  { value: "Textiles", label: "Textiles" },
  { value: "Chemicals", label: "Chemicals" },
  { value: "Fashion", label: "Fashion" },
  { value: "Grocery", label: "Grocery" },
  { value: "Others", label: "Others" },
];

// Commodities options
export const COMMODITIES_OPTIONS = [
  { value: "Gold", label: "Gold" },
  { value: "Silver", label: "Silver" },
  { value: "Crude Oil", label: "Crude Oil" },
  { value: "Natural Gas", label: "Natural Gas" },
  { value: "Copper", label: "Copper" },
  { value: "Iron Ore", label: "Iron Ore" },
  { value: "Wheat", label: "Wheat" },
  { value: "Rice", label: "Rice" },
  { value: "Corn", label: "Corn" },
  { value: "Coffee", label: "Coffee" },
  { value: "Cotton", label: "Cotton" },
  { value: "Sugar", label: "Sugar" },
  { value: "Rubber", label: "Rubber" },
  { value: "Steel", label: "Steel" },
  { value: "Aluminum", label: "Aluminum" },
  { value: "Platinum", label: "Platinum" },
  { value: "Palladium", label: "Palladium" },
  { value: "Diamonds", label: "Diamonds" },
  { value: "Timber", label: "Timber" },
  { value: "Others", label: "Others" },
];

// Company Type options
export const COMPANY_TYPE_OPTIONS = [
  { value: "Private Limited", label: "Private Limited" },
  { value: "Public Limited", label: "Public Limited" },
  { value: "LLC", label: "LLC (Limited Liability Company)" },
  { value: "Partnership", label: "Partnership" },
  { value: "Sole Proprietorship", label: "Sole Proprietorship" },
  { value: "Corporation", label: "Corporation" },
  { value: "Non-Profit", label: "Non-Profit" },
  { value: "Government", label: "Government" },
  { value: "Startup", label: "Startup" },
  { value: "SME", label: "SME (Small & Medium Enterprise)" },
  { value: "Multinational", label: "Multinational" },
  { value: "Others", label: "Others" },
];

// Company Structure options
export const COMPANY_STRUCTURE_OPTIONS = [
  { value: "Flat", label: "Flat" },
  { value: "Hierarchical", label: "Hierarchical" },
  { value: "Matrix", label: "Matrix" },
  { value: "Divisional", label: "Divisional" },
  { value: "Functional", label: "Functional" },
  { value: "Network", label: "Network" },
  { value: "Team-Based", label: "Team-Based" },
  { value: "Hybrid", label: "Hybrid" },
  { value: "Others", label: "Others" },
];
